### ISSUE TITLE
Can I request early access to the code?

### ISSUE THREAD

**Issue by snowface3** [Jeff-Zilence/TransGeo2022#1]
Hi, congrats on your paper acceptance to CVPR. Can I request early access to your code to replicate the results? Thank you

**Comment by Jeff-Zilence** [comment]
Sorry that it is behind schedule. I may not have enough time to clean it, but it should be released by this weekend.

**Comment by Jeff-Zilence** [comment]
The code is out. You may check if there is any bug. Currently it is not very clean, but should be runnable.

**Comment by Jeff-Zilence** [comment]
What is the version of your torchvision and pytorch? Could you upgrade them and try again?

**Comment by Jeff-Zilence** [comment]
https://pytorch.org/vision/main/generated/torchvision.transforms.Resize.html
The resize function should support both PIL and tensor as input, and it works for torchvision==0.11.1+cu113

**Comment by Jeff-Zilence** [comment]
Thank you for your interest. Let me know if you are able to run it.
