### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './result_vigor/attention/train/35112.png'

### ISSUE THREAD

**Issue by ZhiyiHe1997** [Jeff-Zilence/TransGeo2022#10]
hello， thanks for your sharing project.
I meet the same question with [BoopSainy](https://github.com/BoopSainy) when I try to train model on VIGOR.
I changed the code as you modified last month, but it still unable to work.
Can you tell me what should I do to fix it?
Thanks again!

FileNotFoundError: [Errno 2] No such file or directory: './result_vigor/attention/train/35112.png'

**Comment by ZhiyiHe1997** [comment]
Add : therer is no attention map in ./result_vigor/attention/train

**Comment by Jeff-Zilence** [comment]
Thank you for your interest. Could you provide more information? There should not be issue about this, as it has been tested by another user. The current version has addressed this issue and you do not need to modify the code.

**Comment by ZhiyiHe1997** [comment]
Hi, Jeff
Thanks for your reply.
I find that i have made some mistakes when i use --multiprocessing distributed training , which cause the GPU menmory error and  "FileNotFoundError: [Errno 2] No such file or directory: './result_vigor/attention/train/35112.png'".
The code can run without errors on my computer now.
I changed the run_VIGOR.sh script, to use 4 GPUs, I am not sure if this is correct.
Could you give me some advice?
Thanks again!

CUDA_VISIBLE_DEVICES=0,1,2,3
python -u train.py
--dataset vigor
--save_path ./output
--lr 0.00005
--batch-size 16
--dist-url 'tcp://localhost:10001'
--multiprocessing-distributed
--world-size 1
--rank 0
--gpu
--epochs 50
--save_path ./result_vigor
--op sam
--wd 0.03
--mining
--dataset vigor
--cos
--dim 1000
--asam
--rho 2.5

**Comment by ZhiyiHe1997** [comment]
hello, Jeff
Thanks for your reply!
I raised a new issue in your TransGeo2022 repo about how to train the model
with 4 gpus correctly 2 weeks ago, but no answer recived.
I know how busy you are, and how easy the problem is for you.
I stlii want to let you know that I have tried many solutions, but the code
only use the GPU_num=0 to train, which means a cost of several days, I have
4 2080Ti GPUs in my server.
So, could you please tell me how to modify the "run_VIGOR.sh" to make it
work as I wish, or you can send me a new "run_VIGOR.sh"  if it possible.
Thanks very much.
Looking forward to hearing from you.
Best regards

Jeff-Zilence ***@***.***> 于2022年11月29日周二 02:27写道：

**Comment by Jeff-Zilence** [comment]
You can change line32 of train.py. Using mining with multiple gpus could have issues.
