### ISSUE TITLE
Request for Pretrained model for CVUSA Limited FoV.

### ISSUE THREAD

**Issue by MaxorPaxor** [Jeff-Zilence/TransGeo2022#11]
Hello,

First I want to say that I think this is a great work.
I'm looking for a model for CVUSA limited FoV for some experiences, I have seen that you already uploaded one [here](https://github.com/Jeff-Zilence/TransGeo2022/issues/2), but the link has expired.

Could you please reupload it?

Thank you very much.

**Comment by Jeff-Zilence** [comment]
The link should be good now.
