### ISSUE TITLE
How to properly determine the ASAM parameter rho?

### ISSUE THREAD

**Issue by Soyeon11** [Jeff-Zilence/TransGeo2022#12]
Hello, @Jeff-Zilence 

I'm trying to apply ASAM to learning vision transformer for CVGL Task.
I used your ASAM code , and tried to adjst rho within (0.5 - 3.0)
But Test accuracy in Training converged to 0 after 20k step in all cases.

How to properly determine the ASAM parameter rho?
And Have you ever encountered the same phenomenon when applying ASAM while learning Transgeo?

Thank you for your reply.

**Comment by Jeff-Zilence** [comment]
Thank you for your interest. I did a grid search and find that 2.5 has the best performance, but it does not make much difference as long as it is working properly (not too small or too large) for our task. For new tasks, you might need to make sure your code is working well without ASAM, then try to add it with rho in (0.5-3.0). What is the accuracy without ASAM?

**Comment by Soyeon11** [comment]
Thank you for your reply.

When I trained with CVUSA dataset without ASAM, Top1 recall test accuracy is 84.97%.
My code without ASAM works well, but there is a phenomenon that the test loss rises in the interval due to a slight overfitting in the 60k to 130k step. 
When overfitting occurs in that interval, the test accuracy remains slightly lowered, but after that interval overfitting is resolved again and the test accuracy increases.
In order to solve this part, I would like to apply the ASAM used by Transgeo to prevent overfitting.
But when I applied ASAM , Test accuracy in Training converged to 0.

Is there some error in using ASAM?
If you know of other ways to prevent overfitting during training other than ASAM, please let me know.

**Comment by Jeff-Zilence** [comment]
> Thank you for your reply.
> 
> When I trained with CVUSA dataset without ASAM, Top1 recall test accuracy is 84.97%. My code without ASAM works well, but there is a phenomenon that the test loss rises in the interval due to a slight overfitting in the 60k to 130k step. When overfitting occurs in that interval, the test accuracy remains slightly lowered, but after that interval overfitting is resolved again and the test accuracy increases. In order to solve this part, I would like to apply the ASAM used by Transgeo to prevent overfitting. But when I applied ASAM , Test accuracy in Training converged to 0.
> 
> Is there some error in using ASAM? If you know of other ways to prevent overfitting during training other than ASAM, please let me know.

I think you should check your implementation of ASAM. As far as I know, there is nothing wrong with ASAM. This issue is irrelevant to TransGeo.
