### ISSUE TITLE
About Output MLP head layer

### ISSUE THREAD

**Issue by Soyeon11** [Jeff-Zilence/TransGeo2022#13]
Hello, @Jeff-Zilence 

I'm wondering MLP head layer which is applied to cls tocken.
In BERT, Final MLP head layer is used for classification task.
But Solving CVGL task, Why you use Final MLP head layer to cls tocken without using the cls token itself as an output feature??

Is there differences using Final MLP head or not?
I wonder if the task performance changes depending on the feature dimension of the MLP head.

Thank you so much for you apply :)

**Comment by Jeff-Zilence** [comment]
This is just a design to add flexibility to the final output dimension. But you can remove it and see if there is any performance drop. I'll close this issue if there is no other question.

**Comment by Soyeon11** [comment]
thank you for the reply. That answer helped me a lot.

**Comment by whu-lyh** [comment]
Hi @Jeff-Zilence , In the paper, the output of the Transformer heads are concatenated and fed into a MLP projection to generate the global feature, but I could not find the operation in your code. Anything I missed?

**Comment by Jeff-Zilence** [comment]
See the model file. It should be just linear layers.

**Comment by whu-lyh** [comment]
Thanks, you mean [here](https://github.com/Jeff-Zilence/TransGeo2022/blob/main/model/Deit.py#L121)?
