### ISSUE TITLE
Decline in evaluation results

### ISSUE THREAD

**Issue by liguopeng0923** [Jeff-Zilence/TransGeo2022#16]
Hi,

I run you model and codes, and the results in CVUSA and CVACT are normal.
But there are some drops (about 5 points drop from 61.48 to 57.6) in VIGOR, maybe the provided model is not the best one?
[My results](https://github.com/Jeff-Zilence/TransGeo2022/assets/61257834/b0a84ffb-4dae-4bfb-94ea-27e96852f038
)
[Your paper results](https://github.com/Jeff-Zilence/TransGeo2022/assets/61257834/d091ba71-9099-4594-8763-c8618a793aac
)

Besides, did you provide the models for vigor-cross?

Best.

**Comment by Jeff-Zilence** [comment]
You may use run_VIGOR.sh and run_VIGOR_cross.sh to reproduce the results.
