### ISSUE TITLE
super slow when calculating accuracy

### ISSUE THREAD

**Issue by Dou0405** [Jeff-Zilence/TransGeo2022#17]
Hi，**thanks for your nice work**!
I am trying to train on VIGOR dataset following the original run_VIGOR.sh script.
The training process in each epoch goes well,but the time used for calculating accuracy seems too long,you can check this:
<img width="834" alt="a1e6a416de0691ed70a808e699b88fc" src="https://github.com/Jeff-Zilence/TransGeo2022/assets/105620796/c8be62e0-1adf-4b5d-8871-1d211d4380c0">
<img width="297" alt="a14070bca51c3c29e21e78577b0e7ad" src="https://github.com/Jeff-Zilence/TransGeo2022/assets/105620796/f47e89c9-b528-4f8c-b466-f787fc05087f">
<img width="739" alt="687bff0daab6abb1b26908ec17e3117" src="https://github.com/Jeff-Zilence/TransGeo2022/assets/105620796/1dae5675-c143-4670-9444-958e044de213">
One epoch of  training  took about an hour, but calculating accuracy took about **6 hours**.
I haven't made much changes to other files,except adding two lines below in train.py,to respond to an error—OSError: image file is truncated (91 bytes not processed). I only used one rtx3090 for training.
what lead to this？

**Comment by Dou0405** [comment]
btw,there is also a long waiting after "start epoch:[],..."

**Comment by Jeff-Zilence** [comment]
This is not expected. The accuracy computation involves large matrix multiplication and it could be slow if the CPU is slow or the memory is small. You can try making the matrix multiplication smaller or putting it GPU. 
The waiting time after the "start epoch" is also related to the matrix multiplication in the sampler. You can remove "--mining" to avoid using hard sample mining.

**Comment by Dou0405** [comment]
I made some changes according to your suggestion,it helps a lot.
Besides，are there any pretrained models of VIGOR? I failed to find any 'model_best' file of VIGOR in the link you provided in readme.
