### ISSUE TITLE
Link expired for pre-trained limited FOV model

### ISSUE THREAD

**Issue by LukeBriggsDev** [Jeff-Zilence/TransGeo2022#19]
You previously uploaded a limited FOV pre-trained model [here](https://github.com/Jeff-Zilence/TransGeo2022/issues/11). That link has since expired again, would you be willing to re-upload it?

**Comment by Jeff-Zilence** [comment]
Thanks for letting me know. I have put it [here](https://drive.google.com/file/d/1Y_DzrYD_E8w5Lg1f8dCDYCaBB5cbObi_/view?usp=sharing).

**Comment by Jeff-Zilence** [comment]
I will close the issue if there are no further questions.
