### ISSUE TITLE
The model of VIGOR you provide is not the best.

### ISSUE THREAD

**Issue by liguopeng0923** [Jeff-Zilence/TransGeo2022#21]
<img width="1117" alt="image" src="https://github.com/Jeff-Zilence/TransGeo2022/assets/61257834/38e6da62-1c6d-4dcd-a49b-d675dbf3c43e">

<img width="854" alt="image" src="https://github.com/Jeff-Zilence/TransGeo2022/assets/61257834/80e44c33-e9b4-4cd6-96e5-0903d333ec06">

**Comment by Jeff-Zilence** [comment]
This number is just a record. You need to evaluate the model on the dataset to get the true result.

**Comment by Jeff-Zilence** [comment]
I will close the issue if there is no further question.

**Comment by liguopeng0923** [comment]
Fine. But I test the model and  get a similar result.

**Comment by Jeff-Zilence** [comment]
This is weird, but it seems that the "epoch" is 1 there and the model might not be the best. Can you run the run_VIGOR.sh and check the performance?

> Fine. But I test the model and get a similar result.

**Comment by liguopeng0923** [comment]
I just download your model in [here](https://drive.google.com/drive/folders/1oaITF_WJojkNaCMGTkBwNjOASEIEg6Vr?usp=sharing), and show it with ``torch.load``.

Can you check this model with ``torch.load`` ?

**Comment by liguopeng0923** [comment]
My partner also get the similar result.

<img width="664" alt="image" src="https://github.com/Jeff-Zilence/TransGeo2022/assets/61257834/8d12bf88-9bc5-4a7b-88f3-641e0612a020">

**Comment by Jeff-Zilence** [comment]
The model might not be the final one and I could not find it now. But you can train with run_VIGOR.sh and get the model/results.

**Comment by liguopeng0923** [comment]
ok, thanks for your work !!!!
