### ISSUE TITLE
Do I need to download the data set to my computer?

### ISSUE THREAD

**Issue by mksasx** [Jeff-Zilence/TransGeo2022#28]
I want to run this model.But I want to know do I need to download the data set to my computer?

**Comment by Jeff-Zilence** [comment]
Of course you need a dataset to train the model.

**Comment by mksasx** [comment]
I have some problems about running this model，for example the CVUSA dataset loading and how to run this model;I'm doing my Graduation Project.I would appreciate it if I can contact you in Wechat;My wechat is 13613677455;I'm in BUAA;
