### ISSUE TITLE
Graduation Project

### ISSUE THREAD

**Issue by mksasx** [Jeff-Zilence/TransGeo2022#29]
I have some problems about running this model，for example the CVUSA dataset loading and how to run this model;I'm doing my Graduation Project.I would appreciate it if I can contact you in Wechat;My wechat is 13613677455;I'm in BUAA;

**Comment by mksasx** [comment]
hellohello

**Comment by mksasx** [comment]
I would appreciate it if you can reply to me!!!!THX!!!

**Comment by Jeff-Zilence** [comment]
We only reply to academic discussion here. I am afraid I cannot help with your Graduation project.
