### ISSUE TITLE
get stuck after one training iteration

### ISSUE THREAD

**Issue by Sugar1y** [Jeff-Zilence/TransGeo2022#3]
Thankyou for your amazing work,
I had a problem trying the code, the network model seemed to get stuck after one training iteration, did the author have such a problem?
Program did not report an error, the process is still occupied memory running.

![屏幕截图 2022-06-16 201323](https://user-images.githubusercontent.com/74653684/174067553-a739eb01-8bb7-4304-a95b-0e8b8b0d7131.png)

**Comment by Jeff-Zilence** [comment]
I am assuming you are running run_VIGOR.sh. This seems to work well as it runs for a whole epoch and the evaluation result makes sense. Could you give me more details about what happens next? I did not have this kind of issue before.

**Comment by Jeff-Zilence** [comment]
Hi, could you provide more information about this issue? Which script did you run? Does it work now? If no response, I am assuming it has been resolved and I will close this issue.

**Comment by Sugar1y** [comment]
Thank you for your reply.

I tried your code, but after iterating once, it got stuck in the second iteration, there was no error, the background was still running, was the process locked？




---Original---
From: ***@***.***&gt;
Date: Sat, Jun 18, 2022 01:48 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Jeff-Zilence/TransGeo2022] get stuck after one trainingiteration (Issue #3)




 
Hi, could you provide more information about this issue? Which script did you run? Does it work now? If no response, I am assuming it has been resolved and I will close this issue.

**Comment by Jeff-Zilence** [comment]
> Thank you for your reply. I tried your code, but after iterating once, it got stuck in the second iteration, there was no error, the background was still running, was the process locked？
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sat, Jun 18, 2022 01:48 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Jeff-Zilence/TransGeo2022] get stuck after one trainingiteration (Issue #3) Hi, could you provide more information about this issue? Which script did you run? Does it work now? If no response, I am assuming it has been resolved and I will close this issue. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Could you please tell me what command did you use? It is hard to figure out the issue given the limited information. This is for one epoch, not iteration. You may kill the process and try again.
