### ISSUE TITLE
Have semi-positives been used for training?

### ISSUE THREAD

**Issue by Dou0405** [Jeff-Zilence/TransGeo2022#30]
I noticed that in the VIGOR dataset, each query (ground image) not only has one positive satellite image but also has three semi-positives, which are not specifically aligned with the query image. However, I didn't see them being used as positive samples in your code. Can I assume that one query (ground image) is only paired with one satellite image in training？

**Comment by mksasx** [comment]
Hi，I want to ask about the dataset .  I download the CVUSA dataset.But the format of the content inside the dataset doesn't correspond to the way the data is loaded in the code.Do you meet the same question?

**Comment by mksasx** [comment]
About this dataset..
![image](https://github.com/Jeff-Zilence/TransGeo2022/assets/35629227/19f6e9bc-8ac1-4702-b18b-381764d122e8)

**Comment by mksasx** [comment]
About this dataset.
------------------------
CVPR subset-selected
-  bingmap
-  splits
-  streetview
-  all.csv

**Comment by mksasx** [comment]
> I noticed that in the VIGOR dataset, each query (ground image) not only has one positive satellite image but also has three semi-positives, which are not specifically aligned with the query image. However, I didn't see them being used as positive samples in your code. Can I assume that one query (ground image) is only paired with one satellite image in training？

How can I download the vigor?I found the file I downloaded is broken.. Could you help me through my wechat？（13613677455 ）

**Comment by Dou0405** [comment]
@mksasx I think the code provided by the author is running well. Perhaps you should check the dataset's path configuration or refer to the previously closed issues. I am sorry that I have no right to share the VIGOR dataset with you. Please ask the author for help.

**Comment by mksasx** [comment]
@dyx30 I have some problem in running this model. And I want to ask you about some questions . I would appreciate it if you could help me and contact me in wechat.  My wechat number is 13613677455.Thx!!!

**Comment by mksasx** [comment]
@dyx30 Thx！！！

**Comment by Jeff-Zilence** [comment]
> I noticed that in the VIGOR dataset, each query (ground image) not only has one positive satellite image but also has three semi-positives, which are not specifically aligned with the query image. However, I didn't see them being used as positive samples in your code. Can I assume that one query (ground image) is only paired with one satellite image in training？

Yes，in TransGeo，we did  not use the semi positive samples in the VIGOR dataset. Thanks for clarification about the codebase.

**Comment by Jeff-Zilence** [comment]
> Hi，I want to ask about the dataset . I download the CVUSA dataset.But the format of the content inside the dataset doesn't correspond to the way the data is loaded in the code.Do you meet the same question?

Based on my experiments，the code works well on CVUSA dataset. The VIGOR download link is provided by OneDrive and you need stable network connection to download them.

**Comment by mksasx** [comment]
![未命名文件(5)](https://github.com/Jeff-Zilence/TransGeo2022/assets/35629227/3c134116-2bcf-47a9-9aad-0b297e50db39)

**Comment by mksasx** [comment]
What is the format of that all.csv, and why is the latitude and longitude in the one I downloaded, and also missing the ATTENTION folder?
![image](https://github.com/Jeff-Zilence/TransGeo2022/assets/35629227/f39a0318-a975-49f1-a6ba-b054f092ac7b)

**Comment by mksasx** [comment]
@Jeff-Zilence @dyx30

**Comment by mksasx** [comment]
@dyx30

**Comment by mvpj1** [comment]
@mksasx

**Comment by mvpj1** [comment]
@dyx30 I also heve a question

**Comment by mksasx** [comment]
@dyx30

**Comment by mksasx** [comment]
@dyx30 I would appreciate it if you can reply to me ! Thx!!
