### ISSUE TITLE
Dataset Problem

### ISSUE THREAD

**Issue by mksasx** [Jeff-Zilence/TransGeo2022#32]
What is the format of that all.csv, and why is the latitude and longitude in the one I downloaded, and also missing the ATTENTION folder?
![image](https://github.com/Jeff-Zilence/TransGeo2022/assets/35629227/36b6d552-a277-4015-8bb8-73b4b67a5e59)

**Comment by Jeff-Zilence** [comment]
Not sure what you mean. But the CVUSA data seems to be ok.
