### ISSUE TITLE
multi-card training

### ISSUE THREAD

**Issue by mengweibao** [Jeff-Zilence/TransGeo2022#33]
May I ask the author how to set up multi-card training?

**Comment by mksasx** [comment]
@mengweibao What's your question？Maybe I can answer you！！

**Comment by mksasx** [comment]
@mengweibao @Jeff-Zilence

**Comment by Jeff-Zilence** [comment]
The code supports multi-card training, but you might have memory issue if you are using our sampler for hard sample mining. We recommend using one GPU to train the model. You can also disable the --mining for multiple GPUs.
