### ISSUE TITLE
the parameter configuration of the CVACT dataset

### ISSUE THREAD

**Issue by wlfxy** [Jeff-Zilence/TransGeo2022#36]
Hello, I would like to ask about the parameter configuration of the CVACT dataset, similar to python -u train.py --lr 0.0001 --batch-size 32 --dist-url 'tcp://localhost:10001' --multiprocessing-distributed --world-size 1 --rank 0 --epochs 100 --save_ path ./result --op sam --wd 0.03 --mining --dataset cvusa --cos --dim 1000 --asam --rho 2.5。Thank you!

**Comment by Jeff-Zilence** [comment]
Should be exactly the same as CVUSA.

**Comment by wlfxy** [comment]
Thank you
