### ISSUE TITLE
About accuracy

### ISSUE THREAD

**Issue by ssfkfffddj** [Jeff-Zilence/TransGeo2022#39]
Hello, are there any other operations besides the setting provided in the code? Why did my first stage of training on the VIGOR dataset result in only 53%？
The settings I used are as follow(I only changed the batch-size):
python -u train.py --lr 0.00005 --batch-size 16 --dist-url 'tcp://localhost:10001' --multiprocessing-distributed --world-size 1 --rank 0  --epochs 50 --save_path ./result_vigor --op sam --wd 0.03 --mining --dataset vigor --cos --dim 1000 --asam --rho 2.5

**Comment by Jeff-Zilence** [comment]
You will need to tune the lr if the batch size is changed.
