### ISSUE TITLE
Annotation Data

### ISSUE THREAD

**Issue by YangSooRim** [Jeff-Zilence/TransGeo2022#4]
I want to learn with a personal dataset.
Is learning possible without annotation data?
If it is not possible, can you tell me how to get the annotation data?

**Comment by Jeff-Zilence** [comment]
I am not sure what kind of dataset you are referring to. But you will annotation to train the model. For example, street-view images and aerial-view images from the same location are considered as positive pairs. You might use GPS to generate annotation for your personal dataset.
Hope this answers your question.

**Comment by Jeff-Zilence** [comment]
Is there any other questions? If not, I will close this issue.

**Comment by YangSooRim** [comment]
![image](https://user-images.githubusercontent.com/88366891/177232352-dc6fd730-e4b1-48ee-a802-0a8f40ea871d.png)  The annotation data I mentioned was this image. CVUSA provides annotation data by default. My dataset will also have a similar format to CVUSA, so I was wondering if such an annotation process would be necessary. The photograph was taken from the CVUSA paper.

**Comment by Jeff-Zilence** [comment]
Do you mean the third image (segmentation map) is annotation? The segmentation map is not necessary for this task. If you have positive image pairs, you can prepare a list of file names like CVUSA. You may slightly modify the dataloader for CVUSA to run the code for your dataset.

**Comment by YangSooRim** [comment]
Thank you very much for your kind reply. Your answer was very helpful!
