### ISSUE TITLE
training on single GPU

### ISSUE THREAD

**Issue by nsa05605** [Jeff-Zilence/TransGeo2022#41]
Hello,

Using the provided code, can I utilize the VIGOR dataset with a single GPU?

It seems that the args.distributed is applied when either multiprocessing_distributed or world_size > 1, otherwise the training doesn't proceed.

Is it possible to train with a single GPU?

Thank you.

**Comment by Jeff-Zilence** [comment]
You can follow the command in the given bash script. It uses 1 GPU by default.
