### ISSUE TITLE
Polar coordinate conversio

### ISSUE THREAD

**Issue by liangjxiong** [Jeff-Zilence/TransGeo2022#42]
Hello! Can you provide polar coordinate conversion code? What is the size of the street view image input model if polar coordinate conversion is used? I really hope to receive a reply! Thank you for your outstanding work!

**Comment by Jeff-Zilence** [comment]
I guess you mean polar tranform. We did not use polar transform in our paper, please refer to the original SAFA paper for the detail of polar transform.
