### ISSUE TITLE
About CVUSA dataset csv files

### ISSUE THREAD

**Issue by PHChenGit** [Jeff-Zilence/TransGeo2022#43]
Hi,

I noticed that there are some codes try to read train.csv and test.csv files.
I downloaded the CVUSA dataset, but I don't see these 2 files.
May I know how generate these 2 files?
Or, where are they?

Thank you!

**Comment by Jeff-Zilence** [comment]
This is included in the CVUSA dataset. Please ask the author to get the dataset.
