### ISSUE TITLE
about features of train set

### ISSUE THREAD

**Issue by realxuyang** [Jeff-Zilence/TransGeo2022#8]
hi, i'm deeply impressed by your work on geo-localization, and i want to learn more about how VIGOR (method) and TransGeo worked by analyzing the difference between these two network's training features, could you please provide the features of TransGeo 's training set (inferenced by the pre-trained model of both same_area and cross_area on VIGOR dataset), I would appreciate it very much, looking forward to more discussion with you, thank you!

And, I'm now a phd student from school of software, tsinghua university. Can I add your WeChat for further discussion or potential cooperation (If there is a opportunity), looking forward to your reply, thank you!

**Comment by Jeff-Zilence** [comment]
Thank you for your interest. You can use our pretrained model to generate features, but I don't have the features on my machine now.

**Comment by ZhiyiHe1997** [comment]
@realxuyang   I'm now a phd student from The Hong Kong Polytechnic University, we can add WeChat for further discussion or potential cooperation (If there is a opportunity). 
My Wechat is He2914687715
